version: "3"

services:
  terraform:
    image: hashicorp/terraform:1.0.6
    volumes:
      - $HOME/.aws:/root/.aws
      - .:/opt/src
    entrypoint: 
      - terraform
    working_dir: /opt/src/terraform
    environment:
      - AWS_PROFILE