---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=yes
    
    - name: Mount block store
      shell: |
        mkfs.ext4 -E nodiscard /dev/nvme1n1
        mkdir -p /mnt/data
        mount -t ext4 -o defaults,nofail /dev/nvme1n1 /mnt/data
      args:
        creates: /mnt/data

    - name: Configure docker home
      shell: |
        mkdir -p /mnt/data/.docker
        mkdir -p /etc/docker
        echo '{"data-root": "/mnt/data/.docker"}' > /etc/docker/daemon.json
      args:
        creates: /etc/docker/daemon.json

    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg-agent
      
    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker.io

    - name: Add user to docker group
      user:
        name: "{{ansible_user}}"
        group: docker