---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:

    - name: Install AWS CLI
      apt:
        name: awscli
        state: present
        update_cache: yes

    - name: Create workshop directory
      file:
        path: /mnt/data/workshop
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Clone repo with the workshop notebook
      git:
        repo: https://github.com/azavea/foss4g-groundwork-hitl-infra.git
        dest: /mnt/data/workshop/materials
        clone: yes

    - name: Clone special Raster Vision branch
      git:
        repo: https://github.com/jisantuc/raster-vision.git
        dest: /mnt/data/workshop/raster-vision
        version: foss4g
        clone: yes

    - name: Pull Raster Vision container
      shell: |
        docker pull jisantuc/raster-vision-pytorch
        docker tag jisantuc/raster-vision-pytorch raster-vision-pytorch 

    - name: Pull GeoTIFF from s3
      shell: aws s3 cp s3://rasterfoundry-production-data-us-east-1/demo-data/jacksonville.sub.tif /mnt/data/workshop/materials/
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"

    - name: Start notebook server
      shell: RASTER_VISION_NOTEBOOK_DIR=/mnt/data/workshop/materials docker/run --jupyter
      args:
        chdir: /mnt/data/workshop/raster-vision