#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

set -u

function usage() {
    echo -n \
        "Usage: $(basename "$0") COMMAND OPTION[S]
Execute Terraform subcommands
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        case "${1}" in
        plan)
            rm -rf .terraform terraform.tfstate*
            docker-compose run --rm terraform init
            docker-compose run --rm terraform plan \
                -var-file="variables.secret" \
                -out="tfplan"
            ;;
        apply)
            docker-compose run --rm terraform apply tfplan
            ;;
        fmt)
            docker-compose run --rm terraform fmt
            ;;
        *)
            echo "ERROR: I don't have support for that Terraform subcommand!"
            exit 1
            ;;
        esac
    fi
fi
